# Generated by Django 5.2.5 on 2025-08-22 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=3, unique=True)),
                ('curr_symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('state_code', models.CharField(blank=True, max_length=3, null=True)),
                ('gst_code', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='exercise.country')),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_code', models.CharField(blank=True, max_length=10, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('avg_age', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('num_of_adult_males', models.BigIntegerField(blank=True, null=True)),
                ('num_of_adult_females', models.BigIntegerField(blank=True, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='exercise.state')),
            ],
            options={
                'db_table': 'city',
            },
        ),
    ]
