# Generated by Django 5.2.5 on 2025-08-25 10:15

import django.db.models.deletion
from django.db import migrations, models
import random
import uuid

def assign_random_user(apps, schema_editor):
    Country = apps.get_model("exercise", "Country")
    User = apps.get_model("exercise", "User")

    users = list(User.objects.all())
    if not users:
        # If no users exist, create one default user
        user = User.objects.create(
            id=uuid.uuid4(),
            email="default@altiushub.com",
        )
        users = [user]

    for country in Country.objects.all():
        country.my_user = random.choice(users)
        country.save(update_fields=["my_user"])

def reverse_func(apps, schema_editor):
    # In reverse migration, just clear the field
    Country = apps.get_model("exercise", "Country")
    for country in Country.objects.all():
        country.my_user = None
        country.save(update_fields=["my_user"])

class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='my_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='exercise.user'),
        ),
        migrations.RunPython(assign_random_user, reverse_func),
    ]
